//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tp_billing_detail
{
    public int tbd_id { get; set; }
    public string tbd_name { get; set; }
    public string tbd_address { get; set; }
    public string tbd_email { get; set; }
    public string tbd_city { get; set; }
    public Nullable<int> tbd_state_id { get; set; }
    public string tbd_zipcode { get; set; }
    public string tbd_telephone { get; set; }
    public string tbd_delivery_instruction { get; set; }
    public Nullable<int> tbd_cod_id { get; set; }
    public Nullable<bool> tbd_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
}

public partial class tp_cart_detail
{
    public int cd_id { get; set; }
    public Nullable<int> cd_pi_id { get; set; }
    public Nullable<int> cd_ui_id { get; set; }
    public Nullable<int> cd_si_id { get; set; }
    public Nullable<int> cd_pp_id { get; set; }
    public Nullable<int> cd_quantity { get; set; }
    public string cd_takeaway_price { get; set; }
    public Nullable<int> cd_pifd_id { get; set; }
    public string cd_random_number { get; set; }
    public Nullable<bool> cd_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
    public string cd_comment { get; set; }
}

public partial class tp_cart_ingredient_mapping
{
    public int cim_id { get; set; }
    public Nullable<int> cim_cd_id { get; set; }
    public Nullable<int> cim_id_id { get; set; }
    public Nullable<bool> cim_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
    public string cim_id_price { get; set; }
    public Nullable<int> cim_fact_id { get; set; }
}

public partial class tp_city
{
    public int tpci_id { get; set; }
    public string tpci_city_name { get; set; }
    public Nullable<int> tpci_tps_id { get; set; }
}

public partial class tp_config
{
    public int tpc_id { get; set; }
    public string tpc_key { get; set; }
    public string tpc_value { get; set; }
}

public partial class tp_country
{
    public int tpc_id { get; set; }
    public string tpc_country_name { get; set; }
}

public partial class tp_customer_order_details
{
    public int cod_id { get; set; }
    public string cod_order_number { get; set; }
    public Nullable<int> cod_ui_id { get; set; }
    public Nullable<int> cod_sd_id { get; set; }
    public Nullable<System.DateTime> cod_order_placed_time { get; set; }
    public Nullable<System.DateTime> cod_order_wish_time { get; set; }
    public Nullable<System.DateTime> cod_order_actual_delivered_time { get; set; }
    public string cod_total_amount { get; set; }
    public string cod_order_type { get; set; }
    public string cod_order_status { get; set; }
    public Nullable<bool> cod_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
    public string cod_tax { get; set; }
    public string cod_delivery_charge { get; set; }
}

public partial class tp_dailyspecials_offer
{
    public int dso_id { get; set; }
    public string dso_name { get; set; }
    public string dso_description { get; set; }
    public string dso_Offer_code { get; set; }
    public Nullable<int> dso_day { get; set; }
    public Nullable<int> dso_product1_pd_id { get; set; }
    public Nullable<int> dso_product1_quantity { get; set; }
    public Nullable<int> dso_product1_ps_id { get; set; }
    public Nullable<int> dso_product2_pd_id { get; set; }
    public Nullable<int> dso_product2_quantity { get; set; }
    public Nullable<int> dso_product2_ps_id { get; set; }
    public string dso_amount { get; set; }
    public Nullable<bool> dso_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
    public Nullable<System.DateTime> dso_start_date { get; set; }
    public Nullable<System.DateTime> dso_end_date { get; set; }
}

public partial class tp_dollars_offer
{
    public int do_id { get; set; }
    public string do_name { get; set; }
    public string do_description { get; set; }
    public string do_offer_code { get; set; }
    public Nullable<int> do_ps_id { get; set; }
    public string do_amount { get; set; }
    public Nullable<bool> do_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
    public Nullable<System.DateTime> do_start_date { get; set; }
    public Nullable<System.DateTime> do_end_date { get; set; }
}

public partial class tp_feast_forfive_offer
{
    public int ffo_id { get; set; }
    public string ffo_name { get; set; }
    public string ffo_description { get; set; }
    public string ffo_offer_code { get; set; }
    public Nullable<int> ffo_product1_id { get; set; }
    public Nullable<int> ffo_product1_ps_id { get; set; }
    public Nullable<int> ffo_product1_quantity { get; set; }
    public Nullable<int> ffo_product2_pd_id { get; set; }
    public Nullable<int> ffo_product2_quantity { get; set; }
    public Nullable<int> ffo_product3_pd_id { get; set; }
    public Nullable<int> ffo_product3_quantity { get; set; }
    public Nullable<bool> ffo_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
    public string ffo_amount { get; set; }
    public Nullable<System.DateTime> ffo_start_date { get; set; }
    public Nullable<System.DateTime> ffo_end_date { get; set; }
}

public partial class tp_free_pizza_offer
{
    public int fpo_id { get; set; }
    public string fpo_name { get; set; }
    public string fpo_description { get; set; }
    public string fpo_offer_code { get; set; }
    public Nullable<int> fpo_free_product { get; set; }
    public Nullable<int> fpo_free_ps_id { get; set; }
    public Nullable<int> fpo_validate_product { get; set; }
    public Nullable<int> fpo_validate_ingredients { get; set; }
    public Nullable<int> fpo_validate_ps_id { get; set; }
    public Nullable<bool> fpo_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
    public Nullable<System.DateTime> fpo_start_date { get; set; }
    public Nullable<System.DateTime> fpo_end_date { get; set; }
}

public partial class tp_ingredient_category_mapping
{
    public int icm_id { get; set; }
    public Nullable<int> pc_id { get; set; }
    public Nullable<int> id_id { get; set; }
    public Nullable<bool> icm_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
}

public partial class tp_ingredient_details
{
    public int id_id { get; set; }
    public string id_name { get; set; }
    public string id_description { get; set; }
    public string id_price { get; set; }
    public Nullable<bool> id_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
}

public partial class tp_ingredient_product_mapping
{
    public int ipm_id { get; set; }
    public Nullable<int> id_id { get; set; }
    public Nullable<int> pd_id { get; set; }
    public Nullable<bool> iipm_isDefault { get; set; }
    public Nullable<bool> ipm_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
    public Nullable<bool> iipm_IsSingleIngredient { get; set; }
}

public partial class tp_ingredients_product_size_mapping
{
    public int ipsm_id { get; set; }
    public Nullable<int> ipsm_id_id { get; set; }
    public Nullable<int> ipsm_ps_id { get; set; }
    public string ipsm_price { get; set; }
    public Nullable<bool> ipsm_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
}

public partial class tp_newsletter_information
{
    public int nl_id { get; set; }
    public string nl_email { get; set; }
    public Nullable<bool> nl_issubscribed { get; set; }
    public Nullable<bool> nl_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
}

public partial class tp_offer_master
{
    public int om_id { get; set; }
    public string om_name { get; set; }
    public Nullable<int> om_type { get; set; }
    public Nullable<int> om_value { get; set; }
    public string om_offer_code { get; set; }
    public Nullable<bool> om_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
}

public partial class tp_order_product_ingredients_specification
{
    public int opis_id { get; set; }
    public Nullable<int> opis_cod_id { get; set; }
    public Nullable<int> opis_pd_id { get; set; }
    public Nullable<int> opis_id_id { get; set; }
    public Nullable<int> opis_pifd_id { get; set; }
    public Nullable<int> opis_pp_id { get; set; }
}

public partial class tp_order_product_mapping
{
    public int opm_id { get; set; }
    public Nullable<int> opm_cod_id { get; set; }
    public Nullable<int> opm_pd_id { get; set; }
    public string opm_price { get; set; }
    public string opm_Comment { get; set; }
    public Nullable<int> opm_quantity { get; set; }
    public Nullable<int> opm_pp_id { get; set; }
}

public partial class tp_pizza_base_type
{
    public int pbt_id { get; set; }
    public string pbt_name { get; set; }
    public Nullable<bool> pbt_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
}

public partial class tp_product_category
{
    public int pc_id { get; set; }
    public Nullable<int> pc_sd_id { get; set; }
    public string pc_seqno { get; set; }
    public string pc_name { get; set; }
    public Nullable<int> pc_parent { get; set; }
    public string pc_description1 { get; set; }
    public string pc_image_url { get; set; }
    public Nullable<bool> pc_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
}

public partial class tp_product_details
{
    public int pd_id { get; set; }
    public string pd_seqno { get; set; }
    public string pd_name { get; set; }
    public Nullable<int> pd_pc_id { get; set; }
    public string pd_description1 { get; set; }
    public string pd_base_price { get; set; }
    public string pd_image_url { get; set; }
    public Nullable<bool> pd_is_active { get; set; }
    public Nullable<bool> pd_is_delivered { get; set; }
    public Nullable<bool> pd_is_marked_new { get; set; }
    public Nullable<bool> pd_is_marked_speciality { get; set; }
    public Nullable<bool> pd_can_comment { get; set; }
    public Nullable<bool> pd_Is_Commant_Compulsary { get; set; }
    public Nullable<bool> pd_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
    public Nullable<int> pd_sd_id { get; set; }
    public string pp_base_single_ingredients_price { get; set; }
    public string pp_base_double_ingredients_price { get; set; }
    public int no_free_ingredients { get; set; }
}

public partial class tp_product_ingredient_fact_detail
{
    public int pifd_id { get; set; }
    public string pifd_name { get; set; }
    public Nullable<bool> pifd_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
}

public partial class tp_product_ingredient_fact_mapping
{
    public int pifm_id { get; set; }
    public Nullable<int> pd_id { get; set; }
    public Nullable<int> pifd_id { get; set; }
    public Nullable<bool> pifm_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
    public int id_id { get; set; }
}

public partial class tp_product_making_method
{
    public int pmm_id { get; set; }
    public string pmm_name { get; set; }
    public Nullable<bool> pmm_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
}

public partial class tp_product_properties
{
    public int pp_id { get; set; }
    public Nullable<int> ps_id { get; set; }
    public Nullable<int> pd_id { get; set; }
    public Nullable<int> pbt_id { get; set; }
    public Nullable<int> pmm_id { get; set; }
    public string pp_price { get; set; }
    public Nullable<bool> pp_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
    public string pp_single_ingredients_price { get; set; }
    public string pp_double_ingredients_price { get; set; }
}

public partial class tp_product_sizes
{
    public int ps_id { get; set; }
    public string ps_name { get; set; }
    public string ps_description { get; set; }
    public Nullable<bool> ps_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
}

public partial class tp_state
{
    public int tps_id { get; set; }
    public string tps_state_name { get; set; }
    public Nullable<int> tps_tpc_id { get; set; }
}

public partial class tp_store_details
{
    public int sd_id { get; set; }
    public string sd_name { get; set; }
    public Nullable<int> sd_country_id { get; set; }
    public Nullable<int> sd_state_id { get; set; }
    public Nullable<int> sd_city_id { get; set; }
    public string sd_address { get; set; }
    public string sd_contact_number1 { get; set; }
    public string sd_contact_number2 { get; set; }
    public string sd_contact_number3 { get; set; }
    public string sd_contact_number4 { get; set; }
    public string sd_fax_number { get; set; }
    public Nullable<bool> sd_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
}

public partial class tp_store_working_mapping
{
    public int swm_id { get; set; }
    public Nullable<int> swm_sd_id { get; set; }
    public Nullable<int> swm_wd_id { get; set; }
    public Nullable<System.DateTime> swm_start_time { get; set; }
    public Nullable<System.DateTime> swm_end_time { get; set; }
}

public partial class tp_transaction_detail
{
    public int td_id { get; set; }
    public Nullable<int> td_od_id { get; set; }
    public Nullable<System.DateTime> td_transaction_date { get; set; }
    public Nullable<int> Php_Payment_Status { get; set; }
    public string Php_Payment_Amount { get; set; }
    public string Php_PG_Transaction_id { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
}

public partial class tp_user_information
{
    public int ui_id { get; set; }
    public string ui_seqno { get; set; }
    public string ui_firstName { get; set; }
    public string ui_lastName { get; set; }
    public string ui_userName { get; set; }
    public string ui_email { get; set; }
    public string ui_password { get; set; }
    public string ui_mobile { get; set; }
    public string ui_telephone { get; set; }
    public Nullable<int> ui_country_id { get; set; }
    public Nullable<int> ui_state_id { get; set; }
    public string ui_city { get; set; }
    public string ui_pincode { get; set; }
    public Nullable<int> ui_usertype { get; set; }
    public Nullable<int> ui_gender { get; set; }
    public string ui_addressLine1 { get; set; }
    public string ui_addressLine2 { get; set; }
    public string ui_street { get; set; }
    public string ui_house_no { get; set; }
    public Nullable<bool> ui_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
    public Nullable<int> pd_sd_id { get; set; }
}

public partial class tp_working_days
{
    public int wd_id { get; set; }
    public string wd_name { get; set; }
    public Nullable<bool> wd_isdeleted { get; set; }
    public Nullable<int> createdby { get; set; }
    public Nullable<int> modifiedby { get; set; }
    public Nullable<System.DateTime> createdon { get; set; }
    public Nullable<System.DateTime> modifiedon { get; set; }
}
